version: '2'
services:
  server:
    build: server
    ports:
      - "9270:9270"
    links:
      - mongodb
  mongodb:
    build: mongodb
    volumes:
      - /opt/nors/db:/data/db
      - /opt/nors/configdb:/data/configdb
